### ISSUE TITLE
Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'. and Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.

### ISSUE THREAD

**Issue by wallpaperapp2018** [wallpaperapp2018/m3m#1]
--------------gradle code---------------

apply plugin: 'com.android.application'

android {
    android.defaultConfig.vectorDrawables.setUseSupportLibrary(true)
    dexOptions {
        javaMaxHeapSize "4g"
        preDexLibraries false
    }
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.wallpaperhd.app"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 4
        versionName "1.2.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        vectorDrawables {
            useSupportLibrary = true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
        })

    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'de.hdodenhof:circleimageview:2.1.0'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation 'devlight.io:navigationtabbar:1.2.5'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.leo.simplearcloader:simplearcloader:1.0.3'
    implementation 'com.github.jd-alexander:LikeButton:0.2.3'
    implementation 'com.google.code.gson:gson:2.8.0'
    implementation 'com.squareup.retrofit2:retrofit:2.0.2'
    implementation 'com.squareup.retrofit2:converter-gson:2.0.2'
    implementation 'com.squareup.okhttp3:okhttp:3.7.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2'
    implementation 'com.jakewharton.timber:timber:3.1.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.2.0'
    implementation 'com.google.android.gms:play-services-auth:15.0.0'
    implementation 'com.google.firebase:firebase-core:15.0.0'
    implementation 'com.google.firebase:firebase-messaging:15.0.0'
    implementation 'com.google.firebase:firebase-ads:15.0.0'
    implementation 'com.github.vivchar:ViewPagerIndicator:v1.0.1'
    implementation 'com.github.GrenderG:Toasty:1.2.5'
    implementation 'com.anjlab.android.iab.v3:library:1.0.44'
    implementation 'com.facebook.android:facebook-android-sdk:4.32.0'
    implementation 'pl.bclogic:pulsator4droid:1.0.3'
    implementation 'com.jaredrummler:animated-svg-view:1.0.5'
    implementation 'com.miguelcatalan:materialsearchview:1.4.0'
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'

-------------build buildscript------------

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {  url "https://maven.google.com" }
        maven { url "https://jitpack.io" }

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir

**Comment by hbb20** [comment]
Try by changing **testCompile 'junit:junit:4.12'** to **testImplementation 'junit:junit:4.12'** (the last line in your dependencies block). This should solve the problem.



If this issue persists, it means some of the libraries you are using, has not updated to "implementation" in library project. You are using multiple libraries. In that case you will have to check gradle file of each library projects on github (you can skip google's libraries). If they haven't updated to implementation, request them to do so via issue.
